# v2 syntax
version: '2'

# Named volumes
volumes:
  data-volume:
  phplaravel-mysql-data:
    driver: local
services:
  mysql:
    image: mysql:5.7
    build: ./docker/mysql/
    container_name: phplaravel-mysql
    volumes:
      - phplaravel-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=phplaravel
      - MYSQL_DATABASE=phplaravel
      - MYSQL_USER=phplaravel
      - MYSQL_PASSWORD=phplaravel
  queue:
    image: ambientum/php:7.3-nginx
    container_name: phplaravel-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
  app:
    image: ambientum/php:7.3-nginx
    container_name: phplaravel-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
